### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by odow** [jump-dev/MutableArithmetics.jl#106]
One thing we haven't discussed is a 1.0 release for MutableArithmetics prior to MOI. What are the pros/cons of doing this?

**Comment by blegat** [comment]
I think we just need to figure out what to do with https://github.com/jump-dev/MutableArithmetics.jl/issues/107

**Comment by matbesancon** [comment]
Coming back to this, both were solved with the breaking release?

**Comment by blegat** [comment]
Yes, MutableArithmetics should be ready for a 1.0 release. Once it becomes a blocker for MOI v1.0, we should press the button. Meanwhile, we can wait in case a need for breaking changes comes up

**Comment by odow** [comment]
This is now blocking MOI: https://github.com/jump-dev/MathOptInterface.jl/issues/1727

I don't foresee any more breaking changes? We should just bite the bullet on this.

**Comment by blegat** [comment]
Let's bit the bullet

**Comment by odow** [comment]
It's happening: https://github.com/jump-dev/MutableArithmetics.jl/releases/tag/v1.0.0
