### ISSUE TITLE
IsNotMutable

### ISSUE THREAD

**Issue by blegat** [jump-dev/MutableArithmetics.jl#108]
We currently have `IsMutable` and `NotMutable`, we should change it to either
* `Mutable` and `NotMutable` or
* `IsMutable` and `IsNotMutable`.

**Comment by odow** [comment]
I think `Is` is good for traits.

**Comment by blegat** [comment]
Indeed, looking at `IteratorSize` and `IteratorEltype`, their value start with `Is` and `Has`. Should we rename the function `mutability` to `Mutability`?
