### ISSUE TITLE
Clarify alias in operate_to!

### ISSUE THREAD

**Issue by blegat** [jump-dev/MutableArithmetics.jl#139]
This is confusing as BigInt, BigFloat and Rational allow it.
https://github.com/jump-dev/MutableArithmetics.jl/blob/9cd15bc06dba8fde66a984c84aee5c7ed786a6c4/src/interface.jl#L274-L276
The current formulation is confusing should be clarified.
cc @kalmarek

**Comment by odow** [comment]
I find the amount of aliases, re-directs, and shortcuts in MA to be slightly overwhelming:
https://github.com/jump-dev/MutableArithmetics.jl/blob/master/src/shortcuts.jl

This just massively increases the API surface to test. How much of this actually gets used in external packages?
