### ISSUE TITLE
Why is there no mutable assignment operation?

### ISSUE THREAD

**Issue by nsajko** [jump-dev/MutableArithmetics.jl#163]
I'd like it if I could do this:

```
mut = set!!(mut, num)
```

instead of this:

```
mut = zero!!(mut)
mut = add!!(mut, num)
```

Am I missing something?

**Comment by nsajko** [comment]
Similarly, is it possible to do mutable division? Something like `div!!`? How to store the quotient of two BigFloat numbers into a preexisting BigFloat?

**Comment by nsajko** [comment]
I guess maybe it could work like `mut = MA.operate_to!!(mut, copy, num)`, where `copy` is the usual function from `Base`.

**Comment by blegat** [comment]
Yes, `MA.operate_to!(mut, copy, num)` sounds good. In a way, it's already part of the interface since it falls into the generic definition of `copy`, it's just not implemented for `BigInt` yet ^^
