### ISSUE TITLE
`promote_operation_fallback(+, Int64, Irrational)` returns `Int64` instead of `Float64`

### ISSUE THREAD

**Issue by bowenszhu** [jump-dev/MutableArithmetics.jl#164]
```julia
using MutableArithmetics
promote_operation_fallback(+, Int64, Irrational)
```
returns `Int64`

The problem is that `promote_operation_fallback` internally uses `zero` to help type promotion.
https://github.com/jump-dev/MutableArithmetics.jl/blob/5b2a1f01a64fd5a7b0dc3011efd9314e39c95a70/src/interface.jl#L38-L44

However, `zero(::Irrational)` is always `false`, which is the `Bool` version of 0.
See
https://github.com/JuliaLang/julia/blob/742b9abb4dd4621b667ec5bb3434b8b3602f96fd/base/irrationals.jl#L150

As `promote_type(Int64, Irrational)` returns `Float64`, is it possible to change it to use `promote_type(::Type{T}, ::Type{S})`?
See
https://github.com/JuliaLang/julia/blob/f3459234837b13e26abebc22c21d897398151588/base/promotion.jl#L300

**Comment by blegat** [comment]
Thanks for reporting this, it should be fixed by https://github.com/jump-dev/MutableArithmetics.jl/pull/165
