### ISSUE TITLE
How is one supposed to compute the dot product of BigFloat vectors, utilizing mutability?

### ISSUE THREAD

**Issue by nsajko** [jump-dev/MutableArithmetics.jl#189]
I'm trying to optimize the Tulip linear optimizer for the `BigFloat` arithmetic. I noticed that in multiple places in Tulip's source a weighted sum of multiple dot products is computed, so I made a function `dot_weighted_sum_inner` that uses MA. The weights are actually always either `1` or `-1`.

The trouble is, `MA.add_dot` again uses the regular `BigFloat` multiplication and the generic `LinearAlgebra.dot`! See allocation profiling flamegraph screenshot:

![tulip_dot_allocs](https://user-images.githubusercontent.com/4944410/210826339-19cb7344-45f7-4a35-b107-764a5b67c5eb.png)

In the end this results in a slight *increase* in allocation!

How am I supposed to use MA to do this?

**Comment by nsajko** [comment]
I tried to use `LinearAlgebra.dot` instead of `MA.add_dot` and `operate_to!!` instead of `operate!!`, resulting in MA saying that this is not implemented yet. I'll try and add the implementation to `src/implementations/BigFloat.jl`, hope I'll figure out enough of how MA works to do this.

**Comment by nsajko** [comment]
I'm looking into implementing `buffered_operate_to!(::DotBuffer, ::BigFloat, LinearAlgebra.dot, ::AbstractVector{BigFloat}, ::AbstractVector{BigFloat})` using Kahan-Babuska-Neumaier compensated summation, but it seems like the implementation would work not only for BigFloat, but also for BigInt, Rational, and probably all other mutable types, as it only requires basic operations like addition, subtraction and multiplication.

Where should I put this generic implementation of `buffered_operate_to!` for `dot`?

**Comment by nsajko** [comment]
Scratch that, now that I think about that I see that there's no point to compensated summation for exact arithmetics like `BigInt` or `Rational{BigInt}`, so I guess it's OK to keep this specific to `BigFloat` for now.

**Comment by blegat** [comment]
Yes, we can try with `BigFloat` and then see if we can generalize later.
