### ISSUE TITLE
dot with two Hermitian matrices

### ISSUE THREAD

**Issue by blegat** [jump-dev/MutableArithmetics.jl#203]
As notice in https://github.com/jump-dev/JuMP.jl/issues/3242#issuecomment-1445497276, `dot(::Hermitian, ::Hermitian)` does not get redirected in `dispatch.jl`. This means the slow `LinearAlgebra` implementation will get used and allocate a lot of intermediate JuMP expressions.

**Comment by odow** [comment]
Closing as duplicate of #234
