### ISSUE TITLE
question: is MA the place to do type piracy on Base.evalpoly?

### ISSUE THREAD

**Issue by nsajko** [jump-dev/MutableArithmetics.jl#210]
I want to type-pirate `Base.Math.evalpoly(::F, ::Vector{F}) where {F <: BigFloat}` for performance reasons, obviously using `MutableArithmetics`. Since the same code could also be used for `BigInt` and other mutable types, not just for `BigFloat`, I think it would make sense to make the code available for other people to use.

Do you think it would be better if I released this in a separate package, or should I just make a pull request here?

**Comment by odow** [comment]
MA doesn't commit type piracy. Instead, it allows overloads `MA.operate(::typeof(Math.evalpoly), ::Type{T}, args...)`.

@blegat is the person to decide whether it should be added to MA.

**Comment by blegat** [comment]
I agree with @odow about the type piracy and yes, MA is the place for a mutability-aware implementation of evalpoly
