### ISSUE TITLE
feature request: enable optionally mutable operation

### ISSUE THREAD

**Issue by nsajko** [jump-dev/MutableArithmetics.jl#216]
Imagine an API that takes a user-defined function, with the implementation needing to evaluate the function many times.

As the owner of the API, I want to provide the user the option of providing a MA-enabled function, but I don't want to require this. So my implementation should call `MA.buffered_operate_to!!(buf, res, user_defined, x)` if supported, otherwise it should just call `user_defined(x)`. Furthermore, for efficiency I'd prefer for this choice to be based on compile-time dispatch instead of on a try-catch statement.

The problem is that MA doesn't seem to support this currently, calling `MA.buffered_operate_to!!` like above will throw an error, so I think that try-catch is currently the only option.

Perhaps this could be solved by adding another trait that I could use to check whether the function is MA-enabled for a certain type signature?

**Comment by blegat** [comment]
> `MA.buffered_operate_to!!` like above will throw an error, so I think that try-catch is currently the only option.

What is the error, it should work but you may need to implement a few fallback methods like `operate` and `promote_operation`

> Perhaps this could be solved by adding another trait that I could use to check whether the function is MA-enabled for a certain type signature?

`mutability(return_type, op, argument_types...)` does that
https://github.com/jump-dev/MutableArithmetics.jl/blob/3d5ae74a6b3f4dbcd4ac2eea33932a9284f351ce/src/interface.jl#L259-L265

**Comment by nsajko** [comment]
> What is the error
```
julia> import MutableArithmetics

julia> const MA = MutableArithmetics
MutableArithmetics

julia> const F = BigFloat
BigFloat

julia> const user_defined = sin ∘ cos ∘ exp
sin ∘ cos ∘ exp

julia> MA.mutability(F, user_defined, F)
MutableArithmetics.IsMutable()

julia> buf = MA.buffer_for(user_defined, F)

julia> MA.buffered_operate_to!!(buf, BigFloat(), user_defined, big"0.1")
ERROR: `operate_to!(::BigFloat, sin ∘ cos ∘ exp, ::BigFloat)` is not implemented yet.
Stacktrace:
 [1] error(::String, ::String, ::String)
   @ Base ./error.jl:44
 [2] operate_to_fallback!(::MutableArithmetics.IsMutable, output::BigFloat, op::Function, args::BigFloat)
   @ MutableArithmetics ~/tmp/MutableArithmetics.jl/src/interface.jl:330
 [3] operate_to!(output::BigFloat, op::ComposedFunction{ComposedFunction{typeof(sin), typeof(cos)}, typeof(exp)}, args::BigFloat)
   @ MutableArithmetics ~/tmp/MutableArithmetics.jl/src/interface.jl:353
 [4] buffered_operate_to_fallback!(::Nothing, output::BigFloat, op::ComposedFunction{ComposedFunction{typeof(sin), typeof(cos)}, typeof(exp)}, args::BigFloat)
   @ MutableArithmetics ~/tmp/MutableArithmetics.jl/src/interface.jl:456
 [5] buffered_operate_to!(buffer::Nothing, output::BigFloat, op::ComposedFunction{ComposedFunction{typeof(sin), typeof(cos)}, typeof(exp)}, args::BigFloat)
   @ MutableArithmetics ~/tmp/MutableArithmetics.jl/src/interface.jl:472
 [6] buffered_operate_to_fallback!!(::MutableArithmetics.IsMutable, buffer::Nothing, output::BigFloat, op::ComposedFunction{ComposedFunction{typeof(sin), typeof(cos)}, typeof(exp)}, args::BigFloat)
   @ MutableArithmetics ~/tmp/MutableArithmetics.jl/src/interface.jl:634
 [7] buffered_operate_to!!(buffer::Nothing, output::BigFloat, op::ComposedFunction{ComposedFunction{typeof(sin), typeof(cos)}, typeof(exp)}, args::BigFloat)
   @ MutableArithmetics ~/tmp/MutableArithmetics.jl/src/interface.jl:608
 [8] top-level scope
   @ REPL[7]:1
```

> it should work but you may need to implement a few fallback methods like operate and promote_operation. add_mul and add_dot are examples of new operations, you can see which fallback methods are implemented for them.

But we're talking about arbitrary user-defined functions. Surely it shouldn't be necessary to define new MA fallbacks for each one?

**Comment by blegat** [comment]
The default implementation of `mutability(T) isa IsMutable && promote_operation(op, args...) == T` means that if a type is mutable, it is expected to implement the whole mutability API so the error you see for BigFloat is expected.
We prefer not falling back to a non-mutable call as that would silently create slow path that are hard to debug

**Comment by nsajko** [comment]
> We prefer not falling back to a non-mutable call as that would silently create slow path that are hard to debug.

I understand, that's why I proposed a new trait as a possible solution to this problem in the initial message.

To be more specific, you could add something like this to MA; a function called `is_enabled`, with a default to "not enabled":
```julia
abstract type IsEnabledStatus end
struct IsEnabled <: IsEnabledStatus end
struct IsNotEnabled <: IsEnabledStatus end
is_enabled(signature...) = IsNotEnabled()
```

Then `is_enabled` would need to be overloaded for each MA-enabled function. To adapt the example above, the user of my API could, if they implemented MA for their function `user_defined` and the `BigFloat` arithmetic, overload `is_enabled` something like this:
```julia
MA.is_enabled(::Type{F}, ::typeof{user_defined}, ::Type{F}) where {F <: BigFloat} = MA.IsEnabled()
```

Then I could, in the implementation of my API, check whether `user_defined` is MA-enabled by calling `is_enabled`. Something like this:
```julia
call_user_defined(::MA.IsNotEnabled, ::Nothing, ::F, op::Function, x::F) where {F <: BigFloat} = op(x)

call_user_defined(::MA.IsEnabled, buf, res::F, op::Function, x::F) where {F <: BigFloat} =
  MA.buffered_operate_to!!(buf, res, op, x)

call_user_defined(buf, res::F, op::Function, x::F) where {F <: BigFloat} = call_user_defined(
  MA.is_enabled(typeof(res), op, typeof(x)),
  buf,
  res,
  op,
  x,
)
```

This would be much better for me than having to `try`-`catch`.

**Comment by blegat** [comment]
It seems to be exactly the `mutability` trait except that you don't have the default https://github.com/jump-dev/MutableArithmetics.jl/blob/3d5ae74a6b3f4dbcd4ac2eea33932a9284f351ce/src/interface.jl#L259-L265
Removing this default fallback might require adding a lot of implementation to `mutability`. What you can do though is disable it for your user defined operator so that you have the behavior of `is_enabled`, e.g.,
```julia
function mutability(T::Type, ::typeof(user_defined), args::Vararg{Type,N}) where {N}
    return IsNotMutable()
end
```

**Comment by nsajko** [comment]
> What you can do though is disable it for your user defined operator

Interesting, but this isn't acceptable for me because it would mean my users would need to import MA and define a method for `mutability` even if they're not going to take advantage of MA.

On the other hand I guess I could put `is_enabled` into my own package, if you don't want it in MA.

**Comment by nsajko** [comment]
It's registered BTW.

**Comment by blegat** [comment]
Thanks for sharing, it looks interesting, so you solve LPs to find that polynomial ?
We can release MA v1.3 if you think you have everything you need

**Comment by nsajko** [comment]
Thanks, yeah, each LP finds a polynomial, successive LPs are each supposed to yield a better polynomial, until it's good enough.
