### ISSUE TITLE
Mention ArbNumerics (because of ArbFloat type)

### ISSUE THREAD

**Issue by PallHaraldsson** [jump-dev/MutableArithmetics.jl#235]
@JeffreySarnoff Should this package document/point to <s>ArbFloats.jl</s> ArbNumerics.jl as an alternative? It seems they are mutable, and this package not needed:

https://github.com/JuliaArbTypes/ArbFloats.jl/blob/9710fb9b65adff5a62336b6eff50b4d55f378f75/src/type/ArbCstructs.jl#L50   

They are faster that BigFloat, and should be documented in JuliaLang's docs. I found your package there, suggesting to use, since faster than BigFloat, but I think people might overlook even faster option. In case I misunderstand and ArbFloats aren't mutable, then it's an even better reason to point to from here, since can be used together, not as alternatives?

**Comment by JeffreySarnoff** [comment]
[ArbNumerics.jl](https://github.com/JeffreySarnoff/ArbNumerics.jl) is the maintained, newer realization of ArbFloats.jl.  And yes, they should be linked.  If by mutable you mean the value of a variable may be re-assigned, e.g. updated, they are mutable.

**Comment by PallHaraldsson** [comment]
Yes, I meant that one... I'm recalling the ArbFlot type which is there too (I assume moved), so I tend to mix up looking up the older one.

**Comment by odow** [comment]
Sorry for missing this. Where would you expect MutableArithmetics to mention ArbNumerics? It seems they have slightly different goals.

**Comment by odow** [comment]
Closing because I don't know what MutableArithmetics.jl needs to document about ArbNumerics.jl. (The fact that it is a `mutable struct` is unrelated).

One concrete work item might be for `ArbNumerics.jl` to implement the MutableArithmetics API (perhaps as a package extension), but I don't think we want/need to add it to MutableArithmetics.jl. This package is already too complicated.

**Comment by blegat** [comment]
It is being worked on in https://github.com/kalmarek/Arblib.jl/pull/178. We should reference it in the README once this PR is merged
