### ISSUE TITLE
`zero(::BigInt)` is being changed to return a global constant

### ISSUE THREAD

**Issue by nsajko** [jump-dev/MutableArithmetics.jl#250]
JuliaLang/julia/pull/52339

It seems like a good change, but I think some fixes will be required here, and in other code too.

**Comment by odow** [comment]
This seems like a breaking change that shouldn't be merged. Let's discuss in the upstream issue.

**Comment by odow** [comment]
Since it's just a PR and hasn't been merged, I'm going to close this for now. If it gets merged we can re-open this and come up with a plan.
