### ISSUE TITLE
Documentation is generally missing

### ISSUE THREAD

**Issue by kalmarek** [jump-dev/MutableArithmetics.jl#286]
And the remaining one (in README) can be in subtle ways not exactly correct:

README says
> The `MA.operate!!(op::Function, x, args...)` redirects to `op(x, args...)` if `x` is not mutable or if the result of the operation cannot be stored in `x`. Otherwise, it redirects to `MA.operate!(op, x, args...)`.

but actually it redirects only to `MA.operate(op, x, args...)`.

As for the future I'd be great if a tutorial page on implementing e.g. MA for Rationals is provided

**Comment by odow** [comment]
Closing in favor of https://github.com/jump-dev/MutableArithmetics.jl/issues/293
