### ISSUE TITLE
Maybe give some kind of mention to InPlace.jl in the README

### ISSUE THREAD

**Issue by nsajko** [jump-dev/MutableArithmetics.jl#299]
FTR, it appears that the InPlace package is predates MA, and both are based on really quite similar ideas:

https://github.com/tkluck/InPlace.jl

InPlace isn't used much in the ecosystem, and I don't think it's competitive with MA feature-wise, but I guess it'd be nice to give it a shout out.

**Comment by odow** [comment]
PRs accepted
