### ISSUE TITLE
Stackoverflow in SDconstraint

### ISSUE THREAD

**Issue by odow** [jump-dev/MutableArithmetics.jl#86]
x-ref: https://stackoverflow.com/a/67030627/13591160

```julia
using JuMP
model = Model()
E = [1 1; 1 1]
@variable(model, P[1:size(E, 1), 1:size(E, 2)], Symmetric)
julia> @SDconstraint(model, E' * P + P * E + E' * P * E <= 0)
ERROR: StackOverflowError:
Stacktrace:
 [1] mutable_operate!(::typeof(MutableArithmetics.sub_mul), ::Matrix{AffExpr}, ::LinearAlgebra.Symmetric{VariableRef, Matrix{VariableRef}}, ::Matrix{Int64}) (repeats 79984 times)
   @ MutableArithmetics ~/.julia/packages/MutableArithmetics/bPWR4/src/linear_algebra.jl:132
```

**Comment by blegat** [comment]
Seems to be related with https://github.com/jump-dev/MutableArithmetics.jl/issues/84, I don't know what's happening, your code gives me no error on JuMP#master with MOI#master

**Comment by odow** [comment]
This was on 0.21.6. I didn't check `#master`. I recall fixing something like this.

**Comment by blegat** [comment]
I checked with JuMP v0.21.6 and MA v0.2.15 on both Julia 1.6.0 and 1.5.3 and couldn't reproduce the bug either.

**Comment by odow** [comment]
I guess it was fixed by https://github.com/jump-dev/MutableArithmetics.jl/pull/73. I must have been on `MutableArithmetics@0.2.14`. I can't reproduce it now.

Another report: https://discourse.julialang.org/t/moving-from-lmi-toolbox-matlab-to-juliaopt/21001/4?u=odow

**Comment by blegat** [comment]
Indeed, what seems weird is that we got many reported issues just after MA v0.2.15 was released while it was the release fixing it ^^

**Comment by NLaws** [comment]
How do I check which version of MutableArithmetics JuMP is using? And how do I make it update the dependency?

**Comment by odow** [comment]
> How do I check which version of MutableArithmetics JuMP is using?

`] st -m`

> And how do I make it update the dependency?

`] up`
