### ISSUE TITLE
Will there be a new release for julia v1.7.0-DEV compatibility?

### ISSUE THREAD

**Issue by dmbates** [jump-dev/MutableArithmetics.jl#93]
I am able to install the master branch under julia v1.7.0-DEV but I still have problems with installing `MathOptInterface.jl` and, hence, `NLopt.jl`.  Will there be a new release of `MutableArithmetics.jl` soon to allow testing on julia v1.7.0-DEV?  Alternatively, is there a way that I can install the master branch and have other packages like `MathOptInterface.jl` use it rather than the released version?

**Comment by odow** [comment]
> is there a way that I can install the master branch and have other packages like MathOptInterface.jl use it rather than the released version?

In a project:

`] add MutableArithmetics#master`

**Comment by odow** [comment]
Released a new version.
